/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData dashboardCustomize = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insurances = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData legal = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supportAgent = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accounting = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData constructions = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
